### ISSUE TITLE
Error when compiling 1.4.1

### ISSUE THREAD

**Issue by wimco** [Alfresco/alfresco-android-app#246]
Mobile version of Alfresco 1.4.1 on Android is failing with a SQLite error. It is attempting to insert into a table the database does not know about.

It is attempting this in the AccountCursorAdaptor class, in the updateTopText method, line 51.

Anyone have any ideas what's wrong?  Am I missing something?

```

10-27 08:22:25.082: E/SQLiteLog(4338): (1) no such table: statistic_apps
10-27 08:22:25.082: E/SQLiteLog(4338): (1) no such table: statistic_apps
10-27 08:22:25.092: E/SQLiteDatabase(4338): Error inserting count=0 packageName=org.alfresco.mobile.android.application systemApp=-1
10-27 08:22:25.092: E/SQLiteDatabase(4338): android.database.sqlite.SQLiteException: no such table: statistic_apps (code 1): , while compiling: INSERT INTO statistic_apps(count,packageName,systemApp) VALUES (?,?,?)
10-27 08:22:25.092: E/SQLiteDatabase(4338):     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
10-27 08:22:25.092: E/SQLiteDatabase(4338):     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
10-27 08:22:25.092: E/SQLiteDatabase(4338):     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
10-27 08:22:25.092: E/SQLiteDatabase(4338):     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
10-27 08:22:25.092: E/SQLiteDatabase(4338):     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
10-27 08:22:25.092: E/SQLiteDatabase(4338):     at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
10-27 08:22:25.092: E/SQLiteDatabase(4338):     at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1467)
10-27 08:22:25.092: E/SQLiteDatabase(4338):     at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1339)
10-27 08:22:25.092: E/SQLiteDatabase(4338):     at xcxin.filexpert.statistics.app.b.a(Unknown Source)
10-27 08:22:25.092: E/SQLiteDatabase(4338):     at xcxin.filexpert.statistics.app.c.run(Unknown Source)
10-27 08:22:25.262: W/dalvikvm(19493): threadid=1: thread exiting with uncaught exception (group=0x415a3ba8)
10-27 08:22:25.292: W/CursorWrapperInner(19493): Cursor finalized without prior close()
10-27 08:22:25.292: W/CursorWrapperInner(19493): Cursor finalized without prior close()
10-27 08:22:25.292: E/AndroidRuntime(19493): FATAL EXCEPTION: main
10-27 08:22:25.292: E/AndroidRuntime(19493): Process: org.alfresco.mobile.android.application, PID: 19493
10-27 08:22:25.292: E/AndroidRuntime(19493): java.lang.NullPointerException
10-27 08:22:25.292: E/AndroidRuntime(19493):     at org.alfresco.mobile.android.application.accounts.fragment.AccountCursorAdapter.updateTopText(AccountCursorAdapter.java:53)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at org.alfresco.mobile.android.application.accounts.fragment.AccountCursorAdapter.updateTopText(AccountCursorAdapter.java:37)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at org.alfresco.mobile.android.application.fragments.BaseCursorLoader.updateControls(BaseCursorLoader.java:81)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at org.alfresco.mobile.android.application.fragments.BaseCursorLoader.newView(BaseCursorLoader.java:55)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.widget.CursorAdapter.getView(CursorAdapter.java:250)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.widget.AbsSpinner.onMeasure(AbsSpinner.java:193)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.widget.Spinner.onMeasure(Spinner.java:482)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.View.measure(View.java:16497)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.View.measure(View.java:16497)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1226)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.widget.ScrollView.onMeasure(ScrollView.java:326)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.View.measure(View.java:16497)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.View.measure(View.java:16497)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.View.measure(View.java:16497)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.View.measure(View.java:16497)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.View.measure(View.java:16497)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:327)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.View.measure(View.java:16497)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.View.measure(View.java:16497)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1912)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1109)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1291)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.Choreographer.doCallbacks(Choreographer.java:574)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.Choreographer.doFrame(Choreographer.java:544)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.os.Handler.handleCallback(Handler.java:733)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.os.Handler.dispatchMessage(Handler.java:95)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.os.Looper.loop(Looper.java:136)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at android.app.ActivityThread.main(ActivityThread.java:5001)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at java.lang.reflect.Method.invokeNative(Native Method)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at java.lang.reflect.Method.invoke(Method.java:515)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
10-27 08:22:25.292: E/AndroidRuntime(19493):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
10-27 08:22:25.292: E/AndroidRuntime(19493):     
10-27 08:22:25.302: W/ActivityManager(597):   Force finishing activity org.alfresco.mobile.android.application/.activity.MainActivity
10-27 08:22:25.302: W/DropBoxManagerService(597): Dropping: data_app_crash (893 > 0 bytes)
10-27 08:22:25.603: W/WindowManager(597): Screenshot failure taking screenshot for (768x1280) to layer 21035
10-27 08:22:26.103: W/ActivityManager(597): Activity pause timeout for ActivityRecord{429403b8 u0 org.alfresco.mobile.android.application/.activity.MainActivity t20 f}
10-27 08:22:34.763: E/WindowManager(597): Starting window AppWindowToken{430ea0d0 token=Token{427f0ac8 ActivityRecord{429403b8 u0 org.alfresco.mobile.android.application/.activity.MainActivity t20}}} timed out
10-27 08:22:36.194: W/ActivityManager(597): Activity destroy timeout for ActivityRecord{429403b8 u0 org.alfresco.mobile.android.application/.activity.MainActivity t20 f}
10-27 08:22:45.234: W/ActivityManager(597): Timeout executing service: ServiceRecord{42e92cd8 u0 org.alfresco.mobile.android.application/.operations.batch.BatchOperationService}
```

**Comment by jmpascal** [comment]
We higlhy recommend to move to the latest version of Alfresco as a lot of things has changed in this domain.
