### ISSUE TITLE
Android studio Could not find property 'RELEASE_STORE_FILE'

### ISSUE THREAD

**Issue by epm157** [Alfresco/alfresco-android-app#308]
I followed steps provided in: https://github.com/Alfresco/alfresco-android-app/wiki/Prerequisites   to setup Alfresco for Android in Android Studio but after cloning the project Android Studio asks me wether I like to open it and after I accept it goes to gradle build process then I got this error:
Could not find property 'RELEASE_STORE_FILE' on SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null, storeType=null}.

Consult IDE log for more details (Help | Show Log)

**Comment by epm157** [comment]
Incorrect title

**Comment by jmpascal** [comment]
Hello,

The missing keys are private keys we use during the build process and we don't want to check out with the source code. They contain information about how we sign the application and which private key we use for Alfresco Oauth Cloud for example.

We use global *gradle.properties* file to import those key. 
In windows the file is in *C:\Users\username\.gradle* folder

It's possible to use any gradle.properties file (Global or Project) to populate this information or directly overwrite the build.gradle file of the project.

Below you will find a sample of our global gradle.properties.

```properties
RELEASE_STORE_FILE=path/to/your/keystore/
RELEASE_STORE_PASSWORD=password
RELEASE_KEY_ALIAS=alias
RELEASE_KEY_PASSWORD=passowrd

## OAUTH KEYS (only if Alfresco Cloud is required)
OAUTH_API_KEY=
OAUTH_API_SECRET=
OAUTH_CALLBACK=http://www.alfresco.com/mobile-auth-callback.html
OAUTH_SCOPE=public_api
```

The documentation indeed doesn't reflect this process and I will update it asap.

**Comment by epm157** [comment]
Thanks for the reply Pascal. Actually "Getting start"page (https://github.com/Alfresco/alfresco-android-app/wiki/Getting-Started) is incomplete as it includes how to import neither alfresco-android-adk nor samsung-pen-sdk. 
It would be great if we could have a wiki page which we had for setting up Alfresco android app for eclipse(https://wiki.alfresco.com/wiki/Android_:_Setup_Eclipse_Dev_Environment)

**Comment by jmpascal** [comment]
Documentation will improve with feedbacks like yours and I want to thank you to share your experience.

NB : If you found some issue you can also propose a pull request to update it. We will be glad to accept it. The wiki page will soon be mark as obsolete/remove and replaced by information inside the project wiki and github. It would be easy to interact & comment to improve this part.

Regarding modules dependencies everything is now managed by Gradle Build types/variants/flavors. Depending on which build type you selected in Android Studio like [here](https://github.com/Alfresco/alfresco-android-app/wiki/Getting-Started#in-android-studio) some dependencies are associated or not automatically.

Now regarding lib dependencies, generally the alfresco-android-sdk would be retrieved automatically from our maven repository [the latest jar file][1]
Samsung S Pen is a different problem as we are not authorized to redistribute it. So you need to get it from Samsung SDK website.

[1]:https://artifacts.alfresco.com/nexus/service/local/repositories/releases/content/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.0/alfresco-mobile-android-client-api-1.4.0.jar

**Comment by jmpascal** [comment]
Aloah @epm157 

Were informations enough to solve your issue ?

**Comment by epm157** [comment]
@jmpascal 
Finally I could setup Android Studio environment for Alfresco android. Wiki page Eclipse is useful but needs to be updated and modified. 
But unfortunately after running the app I get following : 
04-27 09:33:08.073    8538-8538/org.alfresco.mobile.android.application.debug D/ActivityThread﹕ handleBindApplication:org.alfresco.mobile.android.application.debug
04-27 09:33:08.073    8538-8538/org.alfresco.mobile.android.application.debug D/ActivityThread﹕ setTargetHeapUtilization:0.75
04-27 09:33:08.073    8538-8538/org.alfresco.mobile.android.application.debug D/ActivityThread﹕ setTargetHeapMinFree:2097152
04-27 09:33:08.138    8538-8538/org.alfresco.mobile.android.application.debug D/AndroidRuntime﹕ Shutting down VM
04-27 09:33:08.138    8538-8538/org.alfresco.mobile.android.application.debug W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41aadce0)
04-27 09:33:08.143    8538-8538/org.alfresco.mobile.android.application.debug E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.alfresco.mobile.android.application.debug, PID: 8538
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.alfresco.mobile.android.application.debug/org.alfresco.mobile.android.application.activity.MainActivity}: java.lang.IllegalArgumentException: App ID length must be 32 characters.
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2215)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2264)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5139)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalArgumentException: App ID length must be 32 characters.
            at net.hockeyapp.android.utils.Util.sanitizeAppIdentifier(Util.java:144)
            at net.hockeyapp.android.UpdateManager.register(UpdateManager.java:107)
            at net.hockeyapp.android.UpdateManager.register(UpdateManager.java:94)
            at net.hockeyapp.android.UpdateManager.register(UpdateManager.java:82)
            at net.hockeyapp.android.UpdateManager.register(UpdateManager.java:71)
            at org.alfresco.mobile.android.application.extension.hockeyapp.HockeyAppManagerImpl.checkForUpdates(HockeyAppManagerImpl.java:60)
            at org.alfresco.mobile.android.ui.activity.AlfrescoActivity.onCreate(AlfrescoActivity.java:96)
            at org.alfresco.mobile.android.application.activity.BaseActivity.onCreate(BaseActivity.java:55)
            at org.alfresco.mobile.android.application.activity.MainActivity.onCreate(MainActivity.java:162)
            at android.app.Activity.performCreate(Activity.java:5231)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2264)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5139)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by jmpascal** [comment]
Good point....

You need to comment the line in **\alfresco-mobile-android\build.gradle**
```
    debugCompile project(':extensions:hockeyapp')
```

Hockeyapp is used for debugging & crash reports during our beta phase.
I will try to change the configuration when code is checked out by default.

**Comment by epm157** [comment]
@jmpascal 
Thanks it works now!
I have been working with alfresco android for more than one year now and every time for setting it up I had to browse different documentations and resources(Specially when it comes to Maven dependencies for Eclipse). I wonder if there is way to contribute in updating wiki page of the project so developers who are new do not get confused during this process.

**Comment by jmpascal** [comment]
Honestly Android Maven was (and still is) a great tool but not so easy to play with it and specially in conjunction with Eclipse...

With the creation of Android Studio and integration with Gradle the benefit from Android Maven has shrink a lot. Now the vast majority goes full Android Studio and Gradle. That's why we decided to move to Android studio with Alfresco Mobile 1.5.

Regarding documentation we will deprecate & time to time remove all references with Eclipse & Maven and focus only on Android Studio & Gradle.

The main documentation entry point for app developer will be https://github.com/Alfresco/alfresco-android-app/wiki

To contribute it's simple just edit/create any page of https://github.com/Alfresco/alfresco-android-app/wiki.
It's a public wiki after all ^^

**Comment by huangyoyo** [comment]
How should I solve it? Do not understand

**Comment by arunkiddo** [comment]
Just Remove The Following File i mention @ gradle

 ```
 signingConfigs {
      release {
           storeFile file(RELEASE_STORE_FILE)
          storePassword RELEASE_STORE_PASSWORD
         keyAlias RELEASE_KEY_ALIAS
           keyPassword RELEASE_KEY_PASSWORD
        }
    }
```
